#!/usr/bin/env python3
# Build barcode-data.js from the raw supplier files in ../barcodes/.
#
# The raw files (ASICS order-form CSVs, the ON pricat xlsx) are gitignored and
# NEVER shipped: they contain wholesale prices and order data. This script
# extracts ONLY the barcode map (style/color/size -> EAN) into barcode-data.js,
# which the app loads so users never re-upload barcodes.
#
# Refresh after dropping new files in barcodes/:  python3 tools/build-barcodes.py

import csv, re, os, glob, json
HERE = os.path.dirname(os.path.abspath(__file__))
BARCODES = os.path.join(HERE, '..', 'barcodes')
OUT = os.path.join(HERE, '..', 'barcode-data.js')

def nsize(s):
    """Normalize a size the SAME way the converters' _normUpcSize does in JS:
    '8'->'8', '8.5'->'8.5', 'K12.5'->'K12.5'. Returns None if not a shoe size."""
    s = str(s).strip()
    m = re.match(r'^(K?)(\d{1,2}(\.5)?)$', s, re.I)
    if not m:
        return None
    n = float(m.group(2))
    num = str(int(n)) if n == int(n) else str(n)
    return ('K' if m.group(1) else '') + num

# ---- ASICS: order-form CSVs. Key = "TradingCode-ColorCode|USsize" -> EAN ----
asics = {}
for f in glob.glob(os.path.join(BARCODES, '*.csv')):
    try:
        rows = list(csv.reader(open(f, newline='', encoding='utf-8-sig')))
    except Exception:
        continue
    hi = next((i for i, r in enumerate(rows[:8]) if any('EAN' in str(c) for c in r)), None)
    if hi is None:
        continue
    idx = {str(n).strip(): j for j, n in enumerate(rows[hi])}
    if 'EAN code' not in idx or 'Trading code' not in idx:
        continue
    for r in rows[hi + 1:]:
        def g(n):
            j = idx.get(n)
            return '' if j is None or j >= len(r) else str(r[j]).strip()
        ean, tc, cc, sz = g('EAN code'), g('Trading code').upper(), g('Color code'), nsize(g('Size US'))
        if ean and tc and cc and sz:
            asics[tc + '-' + cc + '|' + sz] = ean

# ---- ON: pricat xlsx. Key = "ItemCode|USsize" -> EAN ----
on = {}
try:
    from openpyxl import load_workbook
    for f in glob.glob(os.path.join(BARCODES, '*.xlsx')):
        ws = load_workbook(f, read_only=True, data_only=True).worksheets[0]
        it = ws.iter_rows(values_only=True)
        hdr = list(next(it)); idx = {n: i for i, n in enumerate(hdr)}
        if 'Item Code' not in idx or 'EAN Barcode' not in idx:
            continue
        for r in it:
            def g(n):
                i = idx.get(n)
                return '' if i is None or i >= len(r) or r[i] is None else str(r[i]).strip()
            code, ean = g('Item Code').upper(), g('EAN Barcode')
            sz = nsize(g('US Size') or g('Size'))
            if code and ean and sz:
                on[code + '|' + sz] = ean
except ImportError:
    print('  (openpyxl not installed — skipping ON pricat)')

data = {'asics': asics, 'on': on}
body = (
    '// AUTO-GENERATED by tools/build-barcodes.py — do not edit by hand.\n'
    '// Barcode maps only (style/color/size -> EAN); no pricing. The raw supplier\n'
    '// files stay in the gitignored barcodes/ folder. Regenerate after adding\n'
    '// files:  python3 tools/build-barcodes.py\n'
    'var BarcodeData = ' + json.dumps(data, separators=(',', ':')) + ';\n'
    "if (typeof module !== 'undefined' && module.exports) module.exports = BarcodeData;\n"
)
open(OUT, 'w').write(body)
print('asics: %d  |  on: %d  ->  barcode-data.js (%.1f KB)' % (
    len(asics), len(on), os.path.getsize(OUT) / 1024))
